language: csharp
solution: MonJobs.sln

env:
  - BIN_SEARCH_PATTERN=tools/mongodb-linux-*/bin
  
install:
  - nuget restore MonJobs.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
  - curl -fsSL https://gist.githubusercontent.com/G3N7/d8c6c2b98e6c9ec36953d0341d8f5d9b/raw/17c83de0e005d905e1fc2cf6289f243d0890e622/patch_assembly_file_with_build_id.sh -o patch_assembly_file_with_build_id.sh
  - bash patch_assembly_file_with_build_id.sh MonJobs/Properties/AssemblyInfo.cs ${TRAVIS_BUILD_NUMBER}
  - bash patch_assembly_file_with_build_id.sh MonJobs.Subscriptions/Properties/AssemblyInfo.cs ${TRAVIS_BUILD_NUMBER}
  - bash patch_assembly_file_with_build_id.sh MonJobs.WebApi/Properties/AssemblyInfo.cs ${TRAVIS_BUILD_NUMBER}

script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.5" MonJobs.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./MonJobs.Tests/bin/Release/MonJobs.Tests.dll
  #- nuget pack ./MonJobs/MonJobs.csproj
  #- nuget pack ./MonJobs.Subscriptions/MonJobs.Subscriptions.csproj
